### ISSUE TITLE
readme is wrong

### ISSUE THREAD

**Issue by micwoj92** [diamondburned/disblob#2]
Why is it written like this that it looks like this is a fork? Makes no sense. The fork info should be removed from #1 before it was merged lol

**Comment by diamondburned** [comment]
PRs welcomed.

**Comment by diamondburned** [comment]
Nevermind.

**Comment by eepykate** [comment]
(He's saying it was just fixed btw)

**Comment by micwoj92** [comment]
Thank you for explaining @GaugeK I would never know this if not your help :)
